### ISSUE TITLE
"Type: Null" photo name incompatible

### ISSUE THREAD

**Issue by WheatiesTM** [ajhyndman/visual-pokemon-calc#3]
Hi ajhyndman! I am also working on a Pokemon web-app and have been using your work as inspiration (hope you don't mind!). Unfortunately I can't clone your repository anymore because the colon in the "Type: Null.jpg" is not allowed on Windows machines. I would appreciate it if you could modify that file name. Thanks!

**Comment by ajhyndman** [comment]
Haha, I knew those filenames would cause trouble eventually.  I'll look into a solution.

Also, super cool that you're working on something too!  I'd love to chat about pokemon code sometime, if you're interested.

**Comment by WheatiesTM** [comment]
Yeah I'd be happy to talk about it once my project is farther along!

**Comment by ajhyndman** [comment]
I think this is fixed now, with 73162d8d14cf22ce35bf4a6ac7831af51f38fae1.

**Comment by ajhyndman** [comment]
I'm closing this, but please re-open if you still have any issues!
